name: Build and output artifacts

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      PVPHUB_MAVEN_USERNAME: "mattmx"
      PVPHUB_MAVEN_SECRET: ${{ secrets.PVPHUB_MAVEN_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
#      - uses: actions/upload-artifact@v3
#        with:
#          name: build-outputs
#          path: build/libs/*-*.jar